# Generated by Django 4.1.7 on 2023-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_story_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
